### PR TITLE
Delete composer.lock

### PR DESCRIPTION
**Pull request by pulzarraider**
Composer.lock should not be part of the library repository.

### CODE REVIEW

**Comment by kevinkhill** [comment]
[I would like to politely disagree with you](https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control) because my understanding is that it's purpose is to be in the repo.

Can you convince me otherwise?

**Comment by BinotaLIU** [comment]
@kevinkhill `composer.lock` will make no effect in libraries. it make effect only on **project** repositories.

**Comment by pulzarraider** [comment]
@kevinkhill For libraries there [is only option to commit the composer.lock](https://getcomposer.org/doc/02-libraries.md#lock-file). In fact most of the libraries do not include it in the repository.

For example:
- [symfony](https://github.com/symfony/symfony)
- [laravel](https://github.com/laravel/laravel) 
They do not include the lock file. 

Reasons to not inlcude the lock file in the library repo:
- tests will always run with the latest dependencies,
- no useless commits to just update the dependencies.

**Comment by kevinkhill** [comment]
I concede and accept your request. Thank you for taking the time to inform me ☺️

**Pull request merged**
